### PR TITLE
Remove Xenial's cloud-archive condition

### PR DESCRIPTION
**Pull request by orviz**

### CODE REVIEW

**Comment by orviz** [comment]
don't remember why it was there, but it was preventing the cloud-archive repository installation for Xenial distros

**Comment by gwarf** [comment]
Hi @orviz you should ask Pablo ;)
https://github.com/EGI-Foundation/ansible-role-cmd/commit/21f014008f24e8aca6560a5cba862010ac697d68

Please also check tests: https://travis-ci.org/EGI-Foundation/ansible-role-cmd/builds/609222535#L527

**Comment by orviz** [comment]
> Hi @orviz you should ask Pablo ;)
> [21f0140](https://github.com/EGI-Foundation/ansible-role-cmd/commit/21f014008f24e8aca6560a5cba862010ac697d68)

https://img.devrant.com/devrant/rant/r_115445_YcizR.jpg

**Comment by orviz** [comment]
Hi @gwarf could you please review this last version? We need it in place in order to validate the Ubuntu version of cloud-info-provider. Thanks!

**Review by gwarf — APPROVED** [review]
LGTM

**Pull request merged**
